# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bay.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'bay.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tbay.proto\x12\x03\x62\x61y\"(\n\nBayRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\t\"2\n\x0b\x42\x61yResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x12\n\nstatusCode\x18\x02 \x01(\x05\x32\x32\n\x03\x42\x61y\x12+\n\x06sayBay\x12\x0f.bay.BayRequest\x1a\x10.bay.BayResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bay_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BAYREQUEST']._serialized_start=18
  _globals['_BAYREQUEST']._serialized_end=58
  _globals['_BAYRESPONSE']._serialized_start=60
  _globals['_BAYRESPONSE']._serialized_end=110
  _globals['_BAY']._serialized_start=112
  _globals['_BAY']._serialized_end=162
# @@protoc_insertion_point(module_scope)
